site_name: Distributed Differentiable Routing (DDR)
site_description: A differentiable routing repo to support the NextGen Framework
repo_url: https://github.com/deepgroundwater/ddr
repo_name: deepgroundwater/ddr
extra_javascript:
  - js/mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - blog:
      authors_profiles: true
      blog_toc: true
      blog_dir: blog
      archive_date_format: MM/dd/yyyy
      archive_url_date_format: MM/dd/yyyy
      post_url_format: "{slug}"

hooks:
  - hooks/socialmedia.py

nav:
  - Home:
    - index.md
    - How to Contribute: home/contributions.md
  - Quick Start:
     - quickstart/index.md
