name: mock
data_sources:
  attributes: s3://mhpi-spatial/hydrofabric_v2.2_attributes/
  hydrofabric_gpkg: mock.gpkg
  conus_adjacency: mock.zarr
  gages_adjacency: mock.zarr
  statistics: ./data/
  streamflow: mock://streamflow/store
  observations: s3://mhpi-spatial/usgs_streamflow_observations/
  gages: mock.csv
experiment:
  batch_size: 1
  start_time: 1981/10/01
  end_time: 1995/09/30
  checkpoint: null
  epochs: 1
  learning_rate:
    '1': 0.005
    '3': 0.001
  rho: 365
  shuffle: true
  warmup: 3
params:
  attribute_minimums:
    velocity: 0.1
    depth: 0.01
    discharge: 0.001
    bottom_width: 0.1
    slope: 0.0001
  parameter_ranges:
    'n':
    - 0.01
    - 0.1
    q_spatial:
    - 0.1
    - 0.9
  defaults:
    p: 1.0
  tau: 7
  save_path: ./
kan:
  hidden_size: 11
  input_var_names:
  - mock
  num_hidden_layers: 1
  learnable_parameters:
  - 'n'
  - q_spatial
  grid: 3
  k: 3
np_seed: 1
seed: 0
device: cpu
s3_region: us-east-1
