defaults:
  - _self_
  - hydra: settings

version: 0.1.1
forcings: merit_conus_v6.18_snow
name: ${version}-ddr_jrb-${forcings}

data_sources:
  conus_hydrofabric: /projects/mhpi/data/hydrofabric/v2.2/conus_nextgen.gpkg
  local_hydrofabric: /projects/mhpi/data/hydrofabric/v2.2/jrb_2.gpkg
  network: /projects/mhpi/tbindas/ddr/data/network.zarr
  transition_matrix: /projects/mhpi/data/hydrofabric/v2.2/conus_transition_matrices.zarr
  statistics: /projects/mhpi/tbindas/ddr/data/statistics
  streamflow:  /projects/mhpi/data/MERIT/streamflow/zarr/${forcings}/73
  observations: /projects/mhpi/data/observations/gages_9000.zarr
  gages: /projects/mhpi/tbindas/ddr/data/gages.csv

eval:
  batch_size: 1
  start_time: 1981/10/01
  end_time: 1995/09/30
  checkpoint: null
  dropout_threshold: null
  epoch: 4
  minimum_zones: 3
  range_bound_lower_bounds:
  - 0.001
  - 0.001
  range_bound_upper_bounds:
  - 0.15
  - 1.0
  rho: 365
  shuffle: true
  warmup: 3

params:
  attributes:
  - mean.impervious
  - mean.elevation
  - mean.smcmax_soil_layers_stag=1
  attribute_minimums:
    discharge: 0.0001
    slope: 0.0001
    velocity: 0.01
    depth: 0.01
    bottom_width: 0.01
  attributes_region:
  - '73'
  parameter_ranges:
    range:
      'n':
      - 0.01
      - 0.35
      q_spatial:
      - 0.0
      - 3.0
  defaults:
    p: 21
  tau: 3
  save_path: ./

np_seed: 1
seed: 0
device: cpu #0

kan:
  hidden_size: 11
  input_var_names:
  - mean.impervious
  - mean.elevation
  - mean.smcmax_soil_layers_stag=1
  num_hidden_layers: 1
  output_size: 3
  learnable_parameters:
  - n
  - q_spatial
  - p_spatial
  grid: 3
  k: 3
