defaults:
  - _self_
  - hydra: settings

version: 0.3.0
forcings: hydrofabric_v2.2_dhbv_retrospective
name: v${oc.env:DDR_VERSION,dev}-ddr-${forcings}

data_sources:
  attributes: s3://mhpi-spatial/hydrofabric_v2.2_attributes/
  hydrofabric_gpkg: /Users/taddbindas/projects/forks/ddr/data/conus_nextgen.gpkg
  conus_adjacency: /Users/taddbindas/projects/forks/ddr/data/conus_adjacency.zarr
  gages_adjacency: /Users/taddbindas/projects/forks/ddr/data/gages_adjacency.zarr
  statistics: /Users/taddbindas/projects/forks/ddr/data
  # streamflow:  s3://mhpi-spatial/hydrofabric_v2.2_dhbv_retrospective
  streamflow: /Users/taddbindas/data/dhbv_hf/retrospective
  observations: s3://mhpi-spatial/usgs_streamflow_observations/
  # observations: /projects/mhpi/data/icechunk/usgs_daily_observations
  gages: /Users/taddbindas//projects/forks/datasets/mhpi/dHBV2.0UH/training_gauges.csv

train:
  batch_size: 2
  start_time: 1981/10/01
  end_time: 1995/09/30
  checkpoint: null
  dropout_threshold: null
  epochs: 100
  learning_rate:
    '0': 0.005
    '3': 0.001
  minimum_zones: 3
  range_bound_lower_bounds:
  - 0.001
  - 0.001
  range_bound_upper_bounds:
  - 0.15
  - 1.0
  rho: 365
  shuffle: true
  warmup: 3

params:
  attributes:

  attribute_minimums:
    discharge: 0.0001
    slope: 0.0001
    velocity: 0.01
    depth: 0.01
    bottom_width: 0.01
  parameter_ranges:
    range:
      'n':
      - 0.01
      - 0.35
      q_spatial:
      - 0.0
      - 3.0
  defaults:
    p: 21
  tau: 3
  save_path: ./

np_seed: 1
seed: 0
device: cpu
s3_region: us-east-2

kan:
  hidden_size: 11
  input_var_names:
    - glaciers
    - aridity
    - meanelevation
    - meanP
    - log_uparea
  num_hidden_layers: 1
  output_size: 3
  learnable_parameters:
  - n
  - q_spatial
  grid: 3
  k: 3
