"""Generate config reference documentation from Pydantic models.

Outputs docs/config_reference.md with tables of all config fields,
their types, defaults, and descriptions.

Usage:
    uv run python scripts/gen_config_docs.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _resolve_type(prop: dict[str, Any], defs: dict[str, Any]) -> str:
    """Convert JSON Schema type info to a readable Python type string."""
    if "$ref" in prop:
        ref_name = prop["$ref"].split("/")[-1]
        return f"`{ref_name}`"
    if "anyOf" in prop:
        types = []
        for item in prop["anyOf"]:
            if "$ref" in item:
                types.append(f"`{item['$ref'].split('/')[-1]}`")
            elif item.get("type") == "null":
                types.append("None")
            else:
                types.append(f"`{item.get('type', '?')}`")
        return " \\| ".join(types)
    if "allOf" in prop:
        refs = [item["$ref"].split("/")[-1] for item in prop["allOf"] if "$ref" in item]
        return " \\& ".join(f"`{r}`" for r in refs) if refs else "?"
    if prop.get("type") == "array":
        item_type = _resolve_type(prop.get("items", {}), defs)
        return f"list[{item_type}]"
    if prop.get("type") == "object":
        return "`dict`"
    return f"`{prop.get('type', '?')}`"


def _format_default(val: Any) -> str:
    """Format a default value for display."""
    if val is None:
        return "—"
    if isinstance(val, str) and len(val) > 40:
        return f"`{val[:37]}...`"
    if isinstance(val, (dict, list)):
        s = json.dumps(val)
        if len(s) > 40:
            return f"`{s[:37]}...`"
        return f"`{s}`"
    return f"`{val}`"


def generate() -> str:
    """Generate Markdown config reference from Pydantic schema."""
    from ddr.validation.configs import Config

    schema = Config.model_json_schema()
    defs = schema.get("$defs", {})

    lines = [
        "# Configuration Reference",
        "",
        "<!-- Auto-generated by scripts/gen_config_docs.py — do not edit manually -->",
        "",
        "All configuration fields for DDR, generated from the Pydantic models in",
        "`src/ddr/validation/configs.py`.",
        "",
    ]

    # Top-level Config fields
    lines.extend(_section_table("Config (top-level)", schema, defs))

    # Sub-models
    for name in ["DataSources", "Params", "ExperimentConfig", "Kan", "AttributeMinimums"]:
        if name in defs:
            lines.extend(_section_table(name, defs[name], defs))

    return "\n".join(lines)


def _section_table(title: str, model_schema: dict[str, Any], defs: dict[str, Any]) -> list[str]:
    """Generate a Markdown table for a single model."""
    props = model_schema.get("properties", {})
    required = set(model_schema.get("required", []))
    desc = model_schema.get("description", "")

    lines = [f"## {title}", ""]
    if desc:
        lines.extend([desc, ""])

    lines.extend(
        [
            "| Field | Type | Default | Required | Description |",
            "|-------|------|---------|----------|-------------|",
        ]
    )

    for field_name, prop in props.items():
        ftype = _resolve_type(prop, defs)
        default = _format_default(prop.get("default"))
        req = "yes" if field_name in required else ""
        description = prop.get("description", "").replace("\n", " ")
        lines.append(f"| `{field_name}` | {ftype} | {default} | {req} | {description} |")

    lines.append("")
    return lines


def main() -> None:
    """Write the config reference to docs/config_reference.md."""
    output = generate()
    out_path = Path(__file__).parent.parent / "docs" / "config_reference.md"
    out_path.write_text(output + "\n")
    print(f"Wrote {out_path} ({len(output)} chars)")


if __name__ == "__main__":
    main()
